### ISSUE TITLE
[Feature Request] Setting position of "Category".

### ISSUE THREAD

**Issue by torakiti2017** [kalilistic/PlayerTrack#104]
Currently, this can be set in "Display"-"Category", but can the UI be changed so that it can be set in "Summary"-"Category"?
After entering a note in "Summay", when setting a category, you have to move to the Display tab, which is a bit time-consuming.

<img width="587" alt="無題" src="https://github.com/kalilistic/PlayerTrack/assets/86459831/569d8e74-f08b-4892-9640-4b5bd88f265f">

**Comment by kalilistic** [comment]
Released with v3.
