### ISSUE TITLE
Unable to restore from backups

### ISSUE THREAD

**Issue by OmegaJackie** [kalilistic/PlayerTrack#121]
Upon launching PlayerTrack, it initiated a restore from the DB but I was shown an error when trying to pull my old data

PlayerTrack Migration Error Log
Failed to migrate players. 
Failed on: _id = 106985
Key = "XAN'A_THUM_91"
LodestoneId = {"$numberLong":"0"}
LodestoneStatus = 0
LodestoneLastUpdated = {"$numberLong":"0"}
LodestoneFailureCount = 0
Names = ["Xan'a Thum"]
HomeWorlds = [{"Key":{"$numberLong":"91"},"Value":"Balmung"}]
Title = ""
FreeCompany = "Rats"
LastTerritoryType = 130
VisibilityType = 0
OverrideFCNameColor = false
Customize = {"$binary":"BAABZAgEBYANKayXGQEBKYACAYC0NQgADIX//w=="}
CustomizeHistory = null
Created = {"$numberLong":"1696240970218"}
Updated = {"$numberLong":"1696240970218"}
SeenCount = 1
Icon = 0
ListColor = null
NamePlateColor = null
Notes = ""
IsAlertEnabled = false
SendNextAlert = {"$numberLong":"1696255370269"}
CategoryId = 1
Tags = []

Failed to insert batch players.
   at PlayerTrack.Migration.LiteDBMigrator.MigratePlayers() in /work/repo/PlayerTrack.Plugin/Migration/LiteDBMigrator.cs:line 955
Migration failed.
Failed to migrate players.
   at PlayerTrack.Migration.LiteDBMigrator.MigratePlayers() in /work/repo/PlayerTrack.Plugin/Migration/LiteDBMigrator.cs:line 1015
   at PlayerTrack.Migration.LiteDBMigrator.Run() in /work/repo/PlayerTrack.Plugin/Migration/LiteDBMigrator.cs:line 86

**Comment by kalilistic** [comment]
Thank you, I have one other report on this. Quick question - what is your db size?

**Comment by OmegaJackie** [comment]
They are 50MB
![image](https://github.com/kalilistic/PlayerTrack/assets/115854606/5deb6e58-5fd2-4903-b662-c93c224afbd4)

**Comment by kalilistic** [comment]
I compared the samples but I'm not seeing a trend yet. I adjusted the player migration code and added some logging. I've submitted this and should hopefully be merged soon. https://github.com/goatcorp/DalamudPluginsD17/pull/2611

Once this is available, can you try again? I believe the error might still happen but I'm hoping you'll get a more specific error message. There are instructions here to migrate fresh. https://github.com/kalilistic/PlayerTrack/wiki/How-to-restore-V2-Database

**Comment by kalilistic** [comment]
The update got approved, should be available now.

**Comment by OmegaJackie** [comment]
I'm not sure how I would go about forcing it to load from a specific backup, I'm not seeing any clear way to allow that

**Comment by OmegaJackie** [comment]
I went ahead and followed the instructions and I got an almost identical error

PlayerTrack Migration Error Log
Failed to migrate players. 
Failed on: _id = 106985
Key = "XAN'A_THUM_91"
LodestoneId = {"$numberLong":"0"}
LodestoneStatus = 0
LodestoneLastUpdated = {"$numberLong":"0"}
LodestoneFailureCount = 0
Names = ["Xan'a Thum"]
HomeWorlds = [{"Key":{"$numberLong":"91"},"Value":"Balmung"}]
Title = ""
FreeCompany = "Rats"
LastTerritoryType = 130
VisibilityType = 0
OverrideFCNameColor = false
Customize = {"$binary":"BAABZAgEBYANKayXGQEBKYACAYC0NQgADIX//w=="}
CustomizeHistory = null
Created = {"$numberLong":"1696240970218"}
Updated = {"$numberLong":"1696240970218"}
SeenCount = 1
Icon = 0
ListColor = null
NamePlateColor = null
Notes = ""
IsAlertEnabled = false
SendNextAlert = {"$numberLong":"1696255370269"}
CategoryId = 1
Tags = []

Failed to insert batch player categories.
   at PlayerTrack.Migration.LiteDBMigrator.MigratePlayers() in /work/repo/PlayerTrack.Plugin/Migration/LiteDBMigrator.cs:line 977
Migration failed.
Failed to migrate players.
   at PlayerTrack.Migration.LiteDBMigrator.MigratePlayers() in /work/repo/PlayerTrack.Plugin/Migration/LiteDBMigrator.cs:line 1023
   at PlayerTrack.Migration.LiteDBMigrator.Run() in /work/repo/PlayerTrack.Plugin/Migration/LiteDBMigrator.cs:line 86

**Comment by OmegaJackie** [comment]
Upon a secondary restart, I was successfully able to restore my backup. appreciate the help.

**Comment by kalilistic** [comment]
Glad to hear it. Did you see any additional errors in the log itself around that time? The log is %appdata%\XIVLauncher\dalamud.log

**Comment by OmegaJackie** [comment]
Not from what I can see, though the log fille is consistently crashing

**Comment by kalilistic** [comment]
Thanks for checking. In case anyone else comes across this, I'm adding an update to allow it to fail up to 10 individual players before it marks the migration as failed. The players that do fail will show up as warnings in the migration log.
