### ISSUE TITLE
Window gets wider each time I open it

### ISSUE THREAD

**Issue by retep998** [kalilistic/PlayerTrack#125]
Using PlayerTrack 3.1.3.0, each time I open the window by using the context menu on a player, the window is wider than last time. Do this a few times and the window can easily become wider than my screen, reaching rather extreme widths.

**Comment by kalilistic** [comment]
Hey, thanks for reporting. I've fixed this locally and will push tomorrow with some other fixes. It happens right now if you're changed the dalamud font size. https://github.com/kalilistic/PlayerTrack/issues/122
