### ISSUE TITLE
[Feature Wishlist]

### ISSUE THREAD

**Issue by F-a-y-t-h** [kalilistic/PlayerTrack#150]
Add a searching to Categories/Tags; or add the ability to assign tags by typing naively again
Encounters; Add Success/Failure/Wipes to the list
Encounters: Add any active duty modifiers to the list aka Join in progress, Unsync, Minilvl, No Echo, Lootmaster
Encounters: Find who who else was in the same Encounter
Tracks if anyone pops a achievement
Restore the appearance tab

Categories/Tags are a bit of a pain right now to reorder and tags could use a bigger char limit

how much of this is doable/viable...

**Comment by kalilistic** [comment]
I'll need to think about things like expanded Encounter tracking - it feels a little out of scope of PlayerTrack. Now, another plugin could integrate with PlayerTrack so it's more seamless.

What do you miss about the Appearance Tab? I think all that's missing is the Height iirc?
How often are you resorting Categories/Tags? If it's often, why?

**Comment by F-a-y-t-h** [comment]
as far as i was aware it was the only place that ever gave a height in cm so it was easier to compare sizes with friends who forgot just what they set it too; a little niche i guess

I generally make a category or tag for any static i sub for and my ocd want to put them together for easier well viewing or any noticeable event if pf (successful clears in challenge runs)

**Comment by kalilistic** [comment]
I think many of these are separate issues. Please raise individual issues for easier tracking if there's anything you'd still like that's not covered by an existing issue.
