### ISSUE TITLE
Characters of a same account

### ISSUE THREAD

**Issue by iv230** [kalilistic/PlayerTrack#162]
As far I understand, there is now on the player object something like an account ID. I think this would be a great addition to the current player data that are stored, in order to allow reaching for every players we met from the account of a giver character.

**Comment by Matuno** [comment]
I'd like this too. I get plenty of obvious alts knocking at my FC's door and that's fine, might even make them a fan, but I'd like to know who's who :x

**Comment by kalilistic** [comment]
I see the value but I do think there's a balance of privacy in this case. I don't plan to use account id at this time.
