### ISSUE TITLE
[Request] Record achievement points when querying lodestone

### ISSUE THREAD

**Issue by Jaksuhn** [kalilistic/PlayerTrack#176]
aside from just being a generally nice addition, it'd also be personally helpful to query the api for so I do not have to reinvent playertrack and have a duplicate db just to utilise that bit of data

**Comment by kalilistic** [comment]
PlayerTrack no longer does any lodestone querying now that content ids are possible. The lodestone is a bit of a mess so I'd like to avoid future integrations with it.
