### ISSUE TITLE
[Bug] Duty replays trigger incorrect player name changes

### ISSUE THREAD

**Issue by Jaksuhn** [kalilistic/PlayerTrack#177]
When going into a duty replay, all players are renamed to their job, but everything else about them is the same. PlayerTrack sees the same players it has seen before and thinks they changed their name to the job title and updates accordingly (or would create new entries for the players if you didn't have playertrack when the recording was made but did when you watched it)

**Comment by kalilistic** [comment]
I think it's a duplicate with https://github.com/kalilistic/PlayerTrack/issues/168

**Comment by Jaksuhn** [comment]
Yes, it is. My bad, was keyword searching and not actually reading fully all the issues
