### ISSUE TITLE
[bug] most options not applying

### ISSUE THREAD

**Issue by hhharkness** [kalilistic/PlayerTrack#179]
hi! so i've gotten the main nameplate colour to apply but the title isn't changing, whether i use inherit category name or set it per player. i would also love - if i got it working - an option to change just the colour of the title rather than the whole nameplate, so that role colours can still apply in duties. this is possible with honorific but i would prefer using just playertrack if possible since adding players is much easier in your plugin.
finally my main issue is that the display settings are not applying in the chat log which is what i assumed they were for - if this isn't the case and they're just meant for the list inside the plugin, would it be possible at all to make them apply to the log? this was my main reason for getting the plugin in the first place as it would be extremely helpful with tracking people's pronouns. i thought at first this was due to me using chat 2 but they don't seem to be applying in the vanilla log either.
thanks in advance! (i debated making separate issues for these but decided not to as they're all related, but let me know if i should anyway)

**Comment by kalilistic** [comment]
It may definitely conflict with other nameplate plugins including honorific, party icons, fcnamecolor, etc. So make sure any of those are disabling and you've restarted your game.

There are no settings right now that apply to chat log. They control the colors inside the playertrack window or the nameplates only.

I do plan to expand configuration options in the future. That being said, the nameplates are more of a convenience feature added by another developer and I don't necessarily want to turn it into a full nameplate customization plugin. Other developers can make plugins that use PlayerTrack's data (via IPC) to do this though.

**Comment by hhharkness** [comment]
forgot to mention, the proximity alert is also not working.

**Comment by kalilistic** [comment]
Can provide some logs as these futures are generally working. So would be something specific going on.

**Comment by hhharkness** [comment]
got the title to work by disabling fc name colour, but still no proximity alert. what is the range for it supposed to be? and how do i access the log 😅
is there any plan to implement chat colours in the future?
