### ISSUE TITLE
Duty recorder messes up with the name change history

### ISSUE THREAD

**Issue by RDalcolmo** [kalilistic/PlayerTrack#184]
When you enter duty recorder, the chat will notify with 

Player Name > JOBNAME

for every player that you met before, keeping that player in the history as that name. The reason is because Duty Recorder changes the player's name to their job.

![{64BCE588-5F07-4102-9EED-53B545D63E42}](https://github.com/user-attachments/assets/44ce4fa6-ff10-4d15-8c80-dbc7245b83de)

Solution: Add a filter to ignore duty recorder name changes

**Comment by cadcof1** [comment]
https://github.com/kalilistic/PlayerTrack/issues/168

**Comment by kalilistic** [comment]
Duplicate with https://github.com/kalilistic/PlayerTrack/issues/168
