### ISSUE TITLE
Different settings/categories for different alts

### ISSUE THREAD

**Issue by NLDGreen** [kalilistic/PlayerTrack#26]
I dunno if PlayerTrack already has a feature like this, but I would like to see the ability to use different settings/categories set for when you are on different characters (like one category for friends of one RP character, another category for friends of an alt RP character, etc)

Though something like this would probably require multiple categories set to one player too...

**Comment by kalilistic** [comment]
I'm not sure I'd be interested in adding this in PlayerTrack given the complexity involved. That being said, I think this could be a good fit for quicklauncher/dalamud to allow people to have their plugin settings per character. I could see that being useful for not just PlayerTrack but other plugins as well.

https://github.com/goatcorp/Dalamud/issues/490
