### ISSUE TITLE
Crash with base game context menu items in friends list

### ISSUE THREAD

**Issue by Tenrys** [kalilistic/PlayerTrack#28]
![image](https://user-images.githubusercontent.com/3979239/130656386-3a4f3b36-b111-4454-ba2c-a0f6c0a94c88.png)
![image](https://user-images.githubusercontent.com/3979239/130656389-b64e498e-f6a5-42b2-98ef-362cb9d267b1.png)

These settings will crash the game if you try to click "Assign Friend Group" on a friend in the friends list. I haven't tested any other configuration. Works fine without setting the context menu items position though.

**Comment by kalilistic** [comment]
This is fixed on testing. Or at least, I disabled the positioning on the friendlist to avoid crashes. Will need to revisit for a proper fix.

**Comment by kalilistic** [comment]
This seems to be a bug in the library I use for context menus. I've reported this to the author.

**Comment by kalilistic** [comment]
This likely was fixed a long time ago but can confirm it's resolved now. :)
