### ISSUE TITLE
Location formatting errors

### ISSUE THREAD

**Issue by Daleterrence** [kalilistic/PlayerTrack#3]
Any duty using a - character in the name results in ???? being displayed in the location field. Example below with Tam-Tara Hard. 
![image](https://user-images.githubusercontent.com/27327941/104064746-6009ed00-51f6-11eb-8f74-bb041f47edc1.png)

**Comment by kalilistic** [comment]
Thanks for the report! Will look into this.

**Comment by kalilistic** [comment]
This is fixed in next release that will be out once merged. Let me know if you still have any issues!
