### ISSUE TITLE
Disable game titles, more control over category/custom titles

### ISSUE THREAD

**Issue by SoeyKitten** [kalilistic/PlayerTrack#34]
I love the feature to override the ingame titles with custom stuff, but it only works when the regular ingame titles are visible. I don't care to see these game titles though as they are just meaningless bloat to me. Also, currently you can either have custom&category title override, or neither.

Would it be possible to give us more granular control over the titles? I'd imagine:
- In the category tab, split up the "Enable nameplate titles" into "Override Nameplate Title with Category Name" and "Override Nameplate Title with Custom Title", with the latter obviously having higher priority if both are set.
- add a new option (either globally in the nameplate settings or as another column in the category settings) to hide regular ingame titles on the nameplate if they have one and neither the category or custom override is set.

Thanks for all your great work!

**Comment by kalilistic** [comment]
Released with v3 (and maybe before).
