### ISSUE TITLE
Auto-delete players / delete categories

### ISSUE THREAD

**Issue by kalilistic** [kalilistic/PlayerTrack#43]
a setting that automatically removes people that are only in the default category and haven't been seen in more than a certain time, like 2 weeks or so.. cause that list is getting loooong for me.  ideally I could pick which categories to cull even.

**Comment by fallynnknivez** [comment]
Please this. Running Bozjan has resulted in a practically unmanageable list.

**Comment by JSharpie** [comment]
I want to add to _not_ auto-delete if 
- You have something written in the `Summary` tab: Tag or Notes
- Character is in a `Category`

Reason: the player could be taking a break from the game.

**Comment by kalilistic** [comment]
A version of this is in V3.1 just pending PRs. This won't run automatically but can review how many records are going to be deleted and clean them up. This might be less of an issue in V3 since performance is (hopefully) significantly improved and database size has been reduced by 50%.

![image](https://github.com/kalilistic/PlayerTrack/assets/35899782/83326ad4-58ea-4af7-aa9e-6d16643d671b)
