### ISSUE TITLE
Player list flooded, no easy way to clean it!

### ISSUE THREAD

**Issue by curtmgray** [kalilistic/PlayerTrack#44]
My player list is flooded with a ton of names. I'd like to wipe it clean and start over. I don't know how to do this though!

**Comment by kalilistic** [comment]
Hey, you can delete %AppData%\XIVLauncher\pluginConfigs\PlayerTrack and it'll remove all your players and categories.

**Comment by curtmgray** [comment]
Awesome! Thanks for that!
