### ISSUE TITLE
Bulk delete.

### ISSUE THREAD

**Issue by LumiWasTaken** [kalilistic/PlayerTrack#47]
A Feature for players who left both options on "Always"

it has cluttered up the selection, especially after a world transfer it might be worth deleting for example everyone without a note / tags or all members of a category.

**Comment by kalilistic** [comment]
This is implemented in v3.1. Just pending PRs.
![image](https://github.com/kalilistic/PlayerTrack/assets/35899782/af7ebb35-3fa1-4866-b527-6980722a6bc1)
