### ISSUE TITLE
Global UI scaling doesn't work properly for some UI elements

### ISSUE THREAD

**Issue by archmage** [kalilistic/PlayerTrack#5]
I've noticed it mostly with dropdowns and the Search feature - here's what it looks like at 1.15.

![image](https://user-images.githubusercontent.com/4102334/111581722-e140ba00-880d-11eb-9fb3-a4481335fb03.png)

You can see the dropdown's arrow is beginning to get cut off. Here's the UI at 1.4.

![image](https://user-images.githubusercontent.com/4102334/111581862-21a03800-880e-11eb-8a8b-75a920d7bb00.png)

The dropdown arrow is gone, and the Search button is close to being inaccessible. At 1.6 it _is_ inaccessible.

![image](https://user-images.githubusercontent.com/4102334/111581940-3a105280-880e-11eb-916e-a946349534ed.png)

This should be a simple matter of adjusting UI element positioning constraints.

**Comment by kalilistic** [comment]
Thanks for the report. I've fixed this and released to my custom repo for now. Will push to official with the next release.
https://github.com/kalilistic/DalamudPluginRepo

**Comment by kalilistic** [comment]
This is now live. Thanks!
