### ISSUE TITLE
[Feature Request] Context Menu option for applicable "(Unable to Retrieve)" Character Entries

### ISSUE THREAD

**Issue by MegaScience** [kalilistic/PlayerTrack#58]
When a character is no longer available - resulting in their entry stating "(Unable to Retrieve)" - the context menu has no PlayerTrack option. Considering these entries still receive relevant tagging such as Friend Group markings, I was hopeful PlayerTrack could still function with these them. I would appreciate being able to check these against information I've kept in PlayerTrack.

If there are concerns with allowing this, I am curious to hear those reasons.

**Comment by kalilistic** [comment]
No concerns about it. I'll just need to check feasibility / how hard it is to do.

**Comment by MegaScience** [comment]
Since just prior to the introduction of Data Center Visits, such users now have their data loaded. As such, this request would center on deleted characters instead of those moved between Data Centers (and any other cases this state might occur, like server-side issues).

**Comment by kalilistic** [comment]
This should now work in the latest ptrack testing (pending merge). This won't work retroactively though, just if PlayerTrack was able to capture their data before.
