### ISSUE TITLE
Notice: Context Menus Removed for Now

### ISSUE THREAD

**Issue by kalilistic** [kalilistic/PlayerTrack#59]
Context Menus are removed for now as they broke with the patch. I hope to add them again.

These include the menu items that show when you right clicked on a player:
- Add/Show Info
- Open Lodestone
- Set Category

**Comment by Aireil** [comment]
It's not ugly at all, it's just the previous and best system, kalilistic is just lazy 👍 .

**Comment by kalilistic** [comment]
Okay, Add/Show and Lodestone menu items are back. Set Category will likely stay gone until we see an official dalamud api for this.
