### ISSUE TITLE
Location instead of note

### ISSUE THREAD

**Issue by xPumaa** [kalilistic/PlayerTrack#6]
I have enabled the alerts with notes, but in the alert the location is the last thing instead of the note.

Plugin version: _v1.1.66_ 

For example:
_[PlayerTrack] Playername last seen 1d ago: The Tower at Paradigm's Breach_

**Comment by kalilistic** [comment]
Hey, at first glance I'm able to see both the note and location. Will try to replicate and fix it for next release.

**Comment by xPumaa** [comment]
Hey, I completely deleted and reconfigured the plugin to avoid errors from previous updates. Unfortunately the note is still missing in the alert.

Steps I made:

1. Backed up all files from playertrack and then deleted them.
2. Started the game and downloaded the current version. (plugin testing builds deactivated)
3. Added a player manually and added a note.
4. Queued unsynced with this player.
5. Waited for an hour.
6. Queued again.


Here is the configuration I used to reproduce:
```
{
  "$type": "PlayerTrack.PluginConfig, PlayerTrack",
  "AlertFrequency": 3600000,
  "BackupFrequency": 14400000,
  "BackupRetention": 10,
  "EnabledIcons": [
    62850,
    62848,
    61722,
    61721,
    62806,
    62841,
    62914,
    62920,
    62137,
    62189
  ],
  "IncludeNotesInAlert": true,
  "LastBackup": 1619857682055,
  "LodestoneCooldownDuration": 3600000,
  "LodestoneFailureDelay": 86400000,
  "LodestoneLocale": 1,
  "LodestoneMaxFailure": 3,
  "LodestoneMaxRetry": 5,
  "LodestoneRequestDelay": 30000,
  "LodestoneTimeout": 60000,
  "NewEncounterThreshold": 86400000,
  "PermittedContent": [],
  "RecentPlayerThreshold": 900000,
  "RestrictInCombat": true,
  "RestrictToContent": true,
  "RestrictToCustom": false,
  "RestrictToHighEndDuty": false,
  "SaveFrequency": 15000,
  "SyncToLodestone": true,
  "UpdateFrequency": 1000,
  "Version": 0,
  "FreshInstall": false,
  "Compressed": true,
  "Enabled": true,
  "PluginLanguage": 0,
  "EnableAlerts": true,
  "AlertDelay": 1000,
  "ShowOverlay": true,
  "SetCurrentTargetOnRightClick": true,
  "SetFocusTargetOnHover": false,
  "ShowPlayerCharacterDetails": true,
  "ShowPlayerOverride": false,
  "LockOverlay": false,
  "PluginVersion": 1166,
  "SelectedCategory": 4,
  "DefaultViewMode": 0
}
```

**Comment by kalilistic** [comment]
Just tested with both automatically and manually added characters and it worked for me. I looked at the code for alerts and don't see an obvious problem yet. https://github.com/kalilistic/PlayerTrack/blob/master/src/PlayerTrack/Service/PlayerService/PlayerService.Notification.cs

For one of these players where the alert failed... can you send their data from players.dat? The sensitive information to censor if you like is name, free company, lodestoneid, actorid, and notes. You'll just need to turn off compression in settings.

```
{"key":"PLAYER_NAME_9=55","value":{"names":["Player Name"],"homeWorlds":[{"id":55}],"freeCompany":"SomeFC","encounters":[{"created":1619881612683,"updated":1619881612683,"location":{"territoryType":1},"job":{}},{"created":1619881721893,"updated":1619881727902,"location":{"territoryType":133},"job":{"id":10,"lvl":80}},{"created":1619881749620,"updated":1619881752617,"location":{"territoryType":133},"job":{"id":10,"lvl":80}}],"notes":"something interesting","lodestone":{"id":12345,"lastUpdated":1619881621731,"status":2},"actorId":123456789,"isManual":true,"alert":{"state":1,"lastSent":1618085534965},"gender":0,"race":5,"tribe":10,"height":100}}
```

**Comment by xPumaa** [comment]
Of course I can send you the data.
```
{"key":"PLAYER_NAME_56","value":{"names":["Player Name"],"homeWorlds":[{"id":56}],"freeCompany":"","encounters":[{"created":1619824066384,"updated":1619824066384,"location":{"territoryType":1},"job":{}},{"created":1619824675126,"updated":1619824692202,"location":{"territoryType":626},"job":{"id":37,"lvl":80}},{"created":1619828431958,"updated":1619828441989,"location":{"territoryType":626},"job":{"id":37,"lvl":80}}],"notes":"Testnote","lodestone":{"id":99999999,"lastUpdated":1619824131421,"status":2},"actorId":999999999,"isManual":true,"alert":{"lastSent":1619828431964},"categoryId":3,"gender":1,"race":4,"tribe":7}}
```
Maybe the deployed version in the plugin repository has the bug?
Here is my local version of the plugin downloaded by the launcher: [PlayerTrack.zip](https://github.com/kalilistic/PlayerTrack/files/6411143/PlayerTrack.zip)

**Comment by kalilistic** [comment]
A little belated but I just released v2 on my custom repo. The alert messages are standardized with the location but you can now right click on the player's name in the alert message to view notes and any other info.
https://github.com/kalilistic/DalamudPluginRepo/raw/master/pluginmaster.json

**Comment by kalilistic** [comment]
This has been pushed to testing now as well. Feel free to reopen or create a new issue if needed.
