### ISSUE TITLE
Optimization is necessary

### ISSUE THREAD

**Issue by Lynvae** [kalilistic/PlayerTrack#60]
I've been using this plugin for quite some time now; 453 days according to the oldest encounter entry I have. With considerable usage since then, the size of the pluginConfigs folder ballooned to 3.25 GB, which seems to be causing issues in the game itself. The plugin frequently causes the game to freeze for up to two seconds, and whenever a player with a large amount of stored encounters changes their information (name/homeworld), the game freezes for up to 10 seconds

**Comment by kalilistic** [comment]
I attempted quite a bit of optimization for V3, can reopen/create a new issue if you still see issues.
