### ISSUE TITLE
Doesn't seem possible to manually add players?

### ISSUE THREAD

**Issue by PrincessRTFM** [kalilistic/PlayerTrack#63]
I know this was previously a feature, being able to search for a player by name and homeworld, but I can't find any such ability now. I have a friend on my list who changed their name but hasn't been picked up by the lodestone change detection (does it only apply when I encounter them and the plugin tries to track them?) and I'd like to manually remove the old entry and add their new name.

**Comment by kalilistic** [comment]
Yeah, dalamud's context menus died on a recent patch so it lost that option. You can still add manually but it's not as intuitive - you can right click on the drop down menu on the main screen. A menu should pop up with a few options.
