### ISSUE TITLE
Lodestone URL (JP) mistake

### ISSUE THREAD

**Issue by KBBBBBB** [kalilistic/PlayerTrack#7]
Click player detail and "Lodestone" link.
But URL is not found.

(NG) https://ja.finalfantasyxiv.com/
(OK) https://jp.finalfantasyxiv.com/

**Comment by kalilistic** [comment]
Ah whoops. I'll be releasing a rewrite (v2) soon and will fix this. Thank you for reporting.

**Comment by KBBBBBB** [comment]
Thank you for your reply!
I'll wait for update :)
