### ISSUE TITLE
Japanese Lodestone Locale

### ISSUE THREAD

**Issue by QHayward** [kalilistic/PlayerTrack#8]
The Japanese Lodestone Locale should be "jp" not "ja".

For example, "https://_ja_.finalfantasyxiv.com/lodestone/character/12345678"
should be changed to "https://_jp_.finalfantasyxiv.com/lodestone/character/12345678"

**Comment by kalilistic** [comment]
Thanks for the report. I have this fixed in a big update that'll be released shortly.

**Comment by kalilistic** [comment]
This should be fixed on v2 that is available on my custom testing repo.
https://github.com/kalilistic/DalamudPluginRepo/raw/master/pluginmaster.json

**Comment by kalilistic** [comment]
This has been pushed to testing now as well. Feel free to reopen or create a new issue if needed.
