### ISSUE TITLE
Name Plate customization is broken

### ISSUE THREAD

**Issue by Werns** [kalilistic/PlayerTrack#80]
Before the updates for 6.2, player name plates were customized based on their assigned category. However, after this plugin was updated, it no longer works. I don't have any other plugins that change nameplates (to my knowledge) and haven't added or removed any since then. I've toggled the settings for it off then on, but they still don't show up.

**Comment by kalilistic** [comment]
Hey, known issue. 6.2 broke nameplates + examine. I hope to add back in the short-term.

**Comment by kalilistic** [comment]
Fixed with v3.
