### ISSUE TITLE
Unable to add new categories

### ISSUE THREAD

**Issue by FrankWan27** [kalilistic/PlayerTrack#83]
Don't seem to be able to add new categories, I'm only able to use the default category

**Comment by kalilistic** [comment]
Can check your dalamud.log to see if any errors or try running /ptrackintegrity.
If you just installed playertrack, might be worth starting fresh by deleting C:\Users\USERNAME\AppData\Roaming\XIVLauncher\pluginConfigs\PlayerTrack\data.

**Comment by FrankWan27** [comment]
reinstalling fixed the problem. (I think the right click context menu wasn't working earlier)
