### ISSUE TITLE
FC Name Color feature broken

### ISSUE THREAD

**Issue by thakyZ** [kalilistic/PlayerTrack#90]
Back during near the end of patch 6.1x the feature for FC Name Color was working. But now I can't seem to get people's name to change for the life of me. This plugin adds the players to the FC Name Color ignore list, which I am not sure if is intended. But it doesn't change the color of the player whatsoever.
https://paste.ee/p/lL6Nk

**Comment by kalilistic** [comment]
Nameplate customization in general broke in 6.2. I've started work on the next major release and will fix this.

**Comment by kalilistic** [comment]
Replaced FCNameColor integration with built-in FC feature. Pending test merge.
